### ISSUE TITLE
Any plan to make datacatalog use stow

### ISSUE THREAD

**Issue by honnix** [lyft/datacatalog#12]
It seems this does not yet support stow. Do you have a plan to support that? I got following error when trying to configure `type` as `stow`:

```
caught panic: type is of an invalid value [stow]
```

@kumare3

**Comment by chanadian** [comment]
It seems that DataCatalog is on an older version of `flyte-stdlib` that is why it doesn’t support `stow` at the moment. I am working on this PR #14 to update the stdlib version and it seems like I will also need to update the go version along with it.

**Comment by chanadian** [comment]
@honnix if you are blocked on this the PR #14 solves this now. We will merge soon. Let us know if you still encounter issues.

**Comment by honnix** [comment]
@chanadian I unfortunately couldn't build an image myself and I believe it is related to https://github.com/mattn/go-sqlite3

Shall we stop supporting sqlite? Otherwise we will need to play with compile options.

**Comment by honnix** [comment]
I submitted a PR to make it compilable https://github.com/lyft/datacatalog/pull/16

**Comment by chanadian** [comment]
Thanks for investigating @honnix. I looked into where we reference `sqlite` and it is an unneeded import. I have opened this PR https://github.com/lyft/datacatalog/pull/17 to fix it and have built this image successfully: docker.io/lyft/datacatalog:2b66cbb89fbc7e217866f45407c452b73409fd05

**Comment by honnix** [comment]
Created a small PR https://github.com/lyft/datacatalog/pull/18 , otherwise I believe we can close this issue.
